# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the Course', primary_key=True, serialize=False)),
                ('cname', models.CharField(help_text='Enter Course Name', max_length=200)),
            ],
        ),
    ]
