# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taco', '0003_auto_20171026_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='aname',
            field=models.CharField(help_text='Enter a name for the Assignment', max_length=200),
        ),
    ]
