# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taco', '0007_auto_20171113_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ta',
            old_name='tname',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='assignmentcommunication',
            name='tid',
        ),
        migrations.RemoveField(
            model_name='ta',
            name='courseOfferingID',
        ),
        migrations.AddField(
            model_name='course',
            name='ta',
            field=models.ManyToManyField(help_text='Select a TA for this course', to='taco.TA'),
        ),
        migrations.AddField(
            model_name='ta',
            name='last_name',
            field=models.CharField(default=1111, help_text='Enter Last Name', max_length=200),
            preserve_default=False,
        ),
    ]
