# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taco', '0013_auto_20171113_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta',
            name='ta',
            field=models.ManyToManyField(to='taco.Assignment'),
        ),
        migrations.AlterField(
            model_name='course',
            name='ta',
            field=models.ManyToManyField(help_text='Select a TA for this course', to='taco.Ta'),
        ),
    ]
