# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taco', '0014_auto_20171116_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ta',
            old_name='ta',
            new_name='assignment',
        ),
        migrations.AlterField(
            model_name='course',
            name='ta',
            field=models.ManyToManyField(help_text='Select a TA for this course', to='taco.Ta'),
        ),
    ]
