# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taco', '0014_auto_20171114_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the Update', primary_key=True, serialize=False)),
                ('ustring', models.CharField(help_text='Enter the Update', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='messagecommunication',
            name='mid',
        ),
        migrations.AlterField(
            model_name='course',
            name='ta',
            field=models.ManyToManyField(help_text='Select a TA for this course', to='taco.Ta'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageCommunication',
        ),
    ]
