# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taco', '0016_auto_20171118_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='desiredCourse',
            field=models.ManyToManyField(help_text="Select a course that you would like to update its TA's", to='taco.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='ta',
            field=models.ManyToManyField(help_text='Select a TA for this course', to='taco.Ta'),
        ),
    ]
