# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taco', '0015_auto_20171116_1415'),
        ('taco', '0022_auto_20171123_0206'),
    ]

    operations = [
    ]
