# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taco', '0024_auto_20171127_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ta',
            field=models.ManyToManyField(help_text='Select a TA for this course', to='taco.Ta'),
        ),
        migrations.RemoveField(
            model_name='ta',
            name='assignment',
        ),
        migrations.AddField(
            model_name='ta',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taco.Assignment'),
        ),
    ]
