# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taco', '0026_auto_20171127_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_hours',
            field=models.IntegerField(default=0, help_text='number of assigned hours'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='worked_hours',
            field=models.IntegerField(default=0, help_text='number of hours worked'),
        ),
        migrations.AlterField(
            model_name='course',
            name='ta',
            field=models.ManyToManyField(help_text='Select a TA for this course', to='taco.Ta'),
        ),
    ]
