# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taco', '0032_auto_20171130_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='desiredCourse',
        ),
        migrations.AddField(
            model_name='ta',
            name='role',
            field=models.CharField(default='TA', help_text='Enter Role', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='ta',
            field=models.ManyToManyField(help_text='Select a TA for this course', to='taco.Ta'),
        ),
        migrations.DeleteModel(
            name='Update',
        ),
    ]
