# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taco', '0034_auto_20171130_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ta',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='ta',
            name='role',
        ),
        migrations.AddField(
            model_name='assignmentcommunication',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taco.Course'),
        ),
        migrations.AddField(
            model_name='assignmentcommunication',
            name='tid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taco.Ta'),
        ),
        migrations.AlterField(
            model_name='course',
            name='ta',
            field=models.ManyToManyField(help_text='Select a TA for this course', to='taco.Ta'),
        ),
    ]
