# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taco', '0005_auto_20171109_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cdescription',
            field=models.TextField(default=1111, help_text='Enter a brief description of the course', max_length=1000),
            preserve_default=False,
        ),
    ]
